name: FTP Test

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        run: |
          echo "Deploying files to the web server"
          rsync -avz --delete ./path/to/local/files/ ${{ secrets.FTP_NAME }}@${{ secrets.FTP_SERVER }}:/home6/thinksurfmedia/repo2.thinksurfmedia.in/repo1/
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
